### PR TITLE
fix: improve .ts tests and avoid clobbering object properties of interfaces

### LINKED ISSUE #243: Draft type clobbers nested object types in typescript 3.1.3
* [X] Issue:
  * Version: 1.7.4
  * _SIMPLE_ Reproduction: [typescript playground](https://www.typescriptlang.org/play/#src=%2F%2F%20Copied%20directly%20from%20immer.d.ts%0D%0A%2F**%20Object%20types%20that%20should%20never%20be%20mapped%20*%2F%0D%0Atype%20AtomicObject%20%3D%0D%0A%20%20%20%20%7C%20Function%0D%0A%20%20%20%20%7C%20Map%3Cany%2C%20any%3E%0D%0A%20%20%20%20%7C%20WeakMap%3Cany%2C%20any%3E%0D%0A%20%20%20%20%7C%20Set%3Cany%3E%0D%0A%20%20%20%20%7C%20WeakSet%3Cany%3E%0D%0A%20%20%20%20%7C%20Promise%3Cany%3E%0D%0A%20%20%20%20%7C%20Date%0D%0A%20%20%20%20%7C%20RegExp%0D%0A%20%20%20%20%7C%20Boolean%0D%0A%20%20%20%20%7C%20Number%0D%0A%20%20%20%20%7C%20String%0D%0A%0D%0A%2F**%20Use%20type%20inference%20to%20know%20when%20an%20array%20is%20finite%20*%2F%0D%0Atype%20IsFinite%3CT%20extends%20any%5B%5D%3E%20%3D%20T%20extends%20never%5B%5D%0D%0A%20%20%20%20%3F%20true%0D%0A%20%20%20%20%3A%20T%20extends%20ReadonlyArray%3Cinfer%20U%3E%20%3F%20(U%5B%5D%20extends%20T%20%3F%20false%20%3A%20true)%20%3A%20true%0D%0A%0D%0Aexport%20type%20DraftObject%3CT%3E%20%3D%20T%20extends%20object%0D%0A%20%20%20%20%3F%20T%20extends%20AtomicObject%20%3F%20T%20%3A%20%7B-readonly%20%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%5BP%5D%3E%7D%0D%0A%20%20%20%20%3A%20T%0D%0A%0D%0Aexport%20type%20DraftArray%3CT%3E%20%3D%20Array%3C%0D%0A%20%20%20%20T%20extends%20ReadonlyArray%3Cany%3E%0D%0A%20%20%20%20%20%20%20%20%3F%20%7B%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%3E%7D%5Bkeyof%20T%5D%0D%0A%20%20%20%20%20%20%20%20%3A%20DraftObject%3CT%3E%0D%0A%3E%0D%0A%0D%0Aexport%20type%20DraftTuple%3CT%20extends%20any%5B%5D%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20T%5Bnumber%5D%20%3F%20Draft%3CT%5BP%5D%3E%20%3A%20never%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Draft%3CT%3E%20%3D%20T%20extends%20any%5B%5D%0D%0A%20%20%20%20%3F%20IsFinite%3CT%3E%20extends%20true%20%3F%20DraftTuple%3CT%3E%20%3A%20DraftArray%3CT%5Bnumber%5D%3E%0D%0A%20%20%20%20%3A%20T%20extends%20ReadonlyArray%3Cany%3E%0D%0A%20%20%20%20%20%20%20%20%3F%20DraftArray%3CT%5Bnumber%5D%3E%0D%0A%20%20%20%20%3A%20T%20extends%20object%20%3F%20DraftObject%3CT%3E%20%3A%20T%0D%0A%2F%2F%20end%20copy%0D%0A%0D%0Ainterface%20State%20%7B%20user%3A%20%7B%20x%3A%20string%20%7D%20%7D%0D%0Atype%20T0%20%3D%20Draft%3CState%3E%0D%0A)
```ts
import { Draft } from "immer";

interface State {
  x: { y: string };
}

type T0 = Draft<State> // $ExpectType State
```
  * Expected behavior: type T0 has type identical to state
  * Observed behavior: type T0 has type { x: any }

The issue stems from the mutual recursion between DraftObject<T> and Draft<T>.
It is reproducible with ([typescript playground](https://www.typescriptlang.org/play/#src=type%20DraftObject%3CT%3E%20%3D%20T%20extends%20object%20%3F%20%7B-readonly%20%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%5BP%5D%3E%7D%20%3A%20T%0D%0Atype%20Draft%3CT%3E%20%3D%20T%20extends%20object%20%3F%20DraftObject%3CT%3E%20%3A%20T%0D%0Atype%20T0%20%3D%20Draft%3C%7B%20x%3A%20%7B%20y%3A%20string%20%7D%20%7D%3E)):
```ts
type DraftObject<T> = T extends object ? {-readonly [P in keyof T]: Draft<T[P]>} : T
type Draft<T> = T extends object ? DraftObject<T> : T
type T0 = Draft<{ x: { y: string } }>
```
where Draft is identical to Draft from immer, but with cases for arrays and tuples removed

### PR DESCRIPTION
**Pull request by aleclarson**
Fixes #243

### CODE REVIEW

**Comment by aleclarson** [comment]
The new tests reveal these (previous uncaught) compiler errors:
```
__tests__/types.ts(138,5): error TS2322: Type '1 & 0' is not assignable to type 'ReadonlyArray<ReadonlyArray<[1, 2]>>'.
  Property 'length' is missing in type 'Number'.
__tests__/types.ts(139,9): error TS2322: Type '1 & 0' is not assignable to type '[1, 2][][]'.
  Property 'length' is missing in type 'Number'.
__tests__/types.ts(159,5): error TS2322: Type '1 & 0' is not assignable to type 'ReadonlyArray<string>'.
  Property 'length' is missing in type 'Number'.
__tests__/types.ts(160,9): error TS2322: Type '1 & 0' is not assignable to type 'string[]'.
  Property 'length' is missing in type 'Number'.
__tests__/types.ts(166,5): error TS2322: Type '1 & 0' is not assignable to type '{ readonly a: ReadonlyArray<string>; }'.
  Property 'a' is missing in type 'Number'.
__tests__/types.ts(167,9): error TS2322: Type '1 & 0' is not assignable to type '{ a: string[]; }'.
  Property 'a' is missing in type 'Number'.
```

**Comment by aleclarson** [comment]
The `DraftTuple<T>` type does not work in TS `2.8.x`-`2.9.x`

Can we wrap each value of a tuple type with `Draft<T>` **and** ensure the draft type is a tuple? Or do we just recommend developers use TS `3.0`+ if they want property tuple drafts?

**Comment by aleclarson** [comment]
IMO: The best option is to bump our `typescript` dependency to `3.0`+ and tell `2.8.x`-`2.9.x` TS users not to upgrade `immer` to `1.8.0+`.

**Comment by mweststrate** [comment]
> IMO: The best option is to bump our `typescript` dependency to `3.0`+ and tell `2.8.x`-`2.9.x` TS users not to upgrade `immer` to `1.8.0+`.

Agreed
